services:
  - name: bundle-server
    url: http://localhost:3000

bundles:
  all:
    service: bundle-server
    resource: bundle.tar.gz
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20
